### ISSUE TITLE
Working with complex helm charts with many microservices

### ISSUE THREAD

**Issue by faheem-cliqz** [windmilleng/tilt#1072] opened 2019-01-30 13:46 UTC
First of all I would like to thank you for sharing this awesome project :) 

I have some interesting use-cases of which some where supported and some I was not able to get working. We can use this issue to have a general discussion.

We have 10s of helm charts for various projects, hosted in a centralized repository (separate from the source) and served through chartmuseum. This is quite a common workflow in the community. Much similar to the community supported helm charts repo. A helm chart can be a combination of deployments, statefulsets and CRDs for various microservices. We also have environment specific values bundled inside helm charts called profiles, to make them portable independent deployment units. A centralized helm chart repo roughly looks something like this: 

```
    kubernetes-charts
    ├── stable
    │   ├── project-x
    │   │   ├── profiles
    │   │   │   ├── production
    │   │   │   │   ├── eu-central-1
    │   │   │   │   │   ├── secrets.yaml
    │   │   │   │   │   ├── values.yaml
    │   │   │   │   │   └── sops.yaml
    │   │   │   │   └── us-east-1
    │   │   │   │       ├── secrets.yaml
    │   │   │   │       ├── values.yaml
    │   │   │   │       └── sops.yaml
    │   │   │   └── dev
    │   │   │       ├── eu-central-1
    │   │   │       ├── secrets.yaml
    │   │   │       ├── values.yaml
    │   │   │       └── sops.yaml
    │   │   ├── templates
    │   │   │   ├── _helpers.tpl
    │   │   │   ├── Notes.txt
    │   │   │   ├── microservice
    │   │   │   │   ├── deployment.yaml
    │   │   │   │   ├── configmap.yaml
    │   │   │   │   ├── service.yaml
    │   │   │   │   ├── ingress.yaml
    │   │   │   │   ├── prometheusrule-recordingrules.yaml
    │   │   │   │   ├── prometheusrule-alerts.yaml
    │   │   │   │   └── servicemonitor.yaml
    │   │   │   ├── dashboards
    │   │   │   │   └── configmap.yaml
    │   │   ├── dashboards
    │   │   │   ├── grafana-dashboard-mydashboard.json
    │   │   │   └── grafana-dashboard-myotherdashboard.json
    │   │   ├── chart.yaml
    │   │   ├── README.md
    │   │   └── values.yaml
    ├── README.rst
    ├── CONTRIBUTING.rst
    ├── Makefile
    └── Jenkinsfile
```

My first problem was with supporting remote helm charts with [helm(pathToChartDir)](https://docs.tilt.build/api.html#api.helm). But that was easily solvable through the addition of [local](https://docs.tilt.build/api.html#api.local) command and using `helm template` command. So my tiltfile looks something like this for fetching the helm charts and rendering them properly with secrets, release names, namespaces etc for a typical project:

```
# Typically we add these defaults in to Makefile for each projects src repo.
# Getting these from Makefile directly would be awesome
pip_index_url = "https://some-private-pypi-repo/simple"
docker_registry = "private-registry.com"
namespace = "myProject"
project_short = "mp"

# Generate release name based on calling user identity
# We have aws IAM identities mapped to k8s users
caller_identity = str(local("aws sts get-caller-identity"))

# Not sure if one can parse json in starlark, but this is a quick hack, but you get a nice release name for a dev working on his instance of application
# Release names are embedded in k8s objects labels, names etc, to differentiate various instances of application running in the same namespace
caller_identity = caller_identity[caller_identity.find("user/") + 5:len(caller_identity) - 4]
release_name = "{}-{}".format(project_short, caller_identity)

# We fetch a helm chart, untar locally and get the profiles with development values
template_script = "helm fetch stable/myProject --untar --untardir ./deploy/helm/ && helm template ./deploy/helm/myProject --namespace {} --name {} -f ./deploy/helm/myProject/profiles/development/eu-central-1/values.yaml".format(namespace, release_name)
yaml_blob = local(template_script)

# Quick docker builds for working on each individual microservice
# Each microservice is a separate folders in root path of the project source repo
# Python component
docker_build(cosmo_image, "cosmo", dockerfile="./cosmo/Dockerfile", build_args={"PIP_INDEX_URL": pip_index_url})
# Python component
docker_build(serving_image, "serving", dockerfile="./serving/Dockerfile", build_args={"PIP_INDEX_URL": pip_index_url})
# Rust component
docker_build(simq_image, "simq", dockerfile="./simq/Dockerfile")

# This is where the problem starts. My first try was to add just a k8s_resource with rendered blob 
k8s_resource("myProject", yaml_blob, port_forwards=8080)
```

Now all my microservice manifests are bundled in to one big rendered yaml blob, rather than separate k8s manifests per microservice as shown above. It would be rather difficult to separate them in to separate yamls as they are bundled into one umbrella chart and those are pretty complex. Most of the examples showcase separate yamls per microservice and having separate `k8s_yaml` statements.

This has an unintended consequence in accordance with the above script that everything shows up under a single name in the UI. All microservices build nicely and are published properly with tilt generated tags, but the pod names change when there are logs streamed from it and then it is not really a nice UX.

Another problem how can we do port_forward per microservice/pod. Does not seems to be possible with my current implementation.

Another problem is with image name and tags and how we typically define them in helm charts. We use a format in spec:

```
    spec:
      containers:
          image: {{ .Values.microservice_name.image.repository }}:{{ .Values.microservice_name.image.tag }}
```

And supply these with different values files based on environment. These seems to be a similar issue to #1059. There is a colon which is part of the template and a tag is injected externally based on environment (in this case development) and leads to a cryptic error: 

```
Error: image registry/project/microservice is not used in any resource
```

Removing all the tags from the templates and making the image name the same as the ref. Seems to work but is not useful anymore. It would be nice to have a scenario, where by some microservices are locked to a specific version which can be stable, and others which one is working on will have there tags automatically generated by tilt or even passed in by a custom function written in titfile to comply with different tagging notations. These can important because we have certain lifecycle rules on docker registry to cleanup images and then can be different from tilt tagging format. But this is a small nit pick.

Also sometimes I have seen during incremental updates to code and restarting/spawning of new pods the ui loses track of which pod is the current running pod and will still try to get logs of a non existent pod and will fail continuously. 

In other cases during network failures from client machine or an elb in front of the api server closing long running tcp connections, logs are no longer being streamed or retried and you get a nice EOF message.

These are some of the things I have seen from my experience, from a day of playing with tilt. If you need more context or support I can certainly provide some. I would definitely like to figure out the big helm chart deployment and tagging problems. Thanks again for the awesome tool :)

**Comment by nicks** [comment] 2019-02-04 17:57
hi @faheem-cliqz !

Sorry for the delay. I thought somebody was already talking to you outside this issue thread.

So this is a big issue report with a lot of questions, comments, and requests in it. Let me try to break out the big themes.

1) Yes, `local()` is a great way to weave together more complicated configs when the other Tiltfile builtins don't get you quite what you want. 

(Personally, I'm hoping we'll eventually have a "standard" way to do common patterns here, like fetching remote helm charts, or substituting in a custom namespace. But this is the best way to do it for now!)

2) It's also OK to have one big YAML! Tilt doesn't care if you have one k8s_yaml statement or many. We break up resources in the UX based on what images you're building locally. Eventually, we want you to be able to describe in the Tiltfile how to group resources together in the UI, completely independently of where those resources are in the YAML.

3) The tagging issues in https://github.com/windmilleng/tilt/issues/1059 should be fixed now, so you should try them out and see if they resolve your problem?

4) Ya, we still need to work on the stability of log streaming + navigation, and any tips you have on how to reproduce would be helpful!

Overall, Tilt is definitely a work in progress, and getting better every day. We do want it to support very complex charts.

How would you like to see this issue addressed in the short-term? We can break out some of the issues into separate tickets? Or did you just want reassurance that these are all use-cases we want to support?

**Comment by nicks** [comment] 2019-03-06 21:25
I'm going to close this issue since I haven't heard any response. I _think_ most of the issues here are addressed or actively being addressed, but let us know if you need anything else!

**Closed by nicks** 2019-03-06 21:25 UTC
