### ISSUE TITLE
Changing kubectl context externally causes tilt to start putting images into new cluster

### ISSUE THREAD

**Issue by majelbstoat** [windmilleng/tilt#1929] opened 2019-07-27 19:33 UTC
If you change the kube context cluster once tilt is running, tilt will start serving images into the new cluster. This technically makes sense, but is still unexpected, and I would suggest, not ideal.

Repro:

Start tilt for local dev:

```
kubectl config use-context docker-desktop
tilt up
```

Change kubectl context to production to debug a problem:

```
kubectl config use-context my-production-env
```

Expected behaviour:

Tilt continues to help serve the local development cluster.

Actual behaviour:

Tilt puts dev images and tilt-synclets into the production cluster.

Perhaps there could be some way to pin the context once tilt starts, to avoid this ambiguity?

**Comment by landism** [comment] 2019-07-29 15:21
Thanks for the report!

Tilt already pins the kube context on startup, and I was unable to reproduce the described behavior using a simple rebuild.

> Tilt puts dev images and tilt-synclets into the production cluster.
Are you talking about docker images being pushed, the k8s objects being applied, or both?

This presumably means one of:
1. There's some way in which Tilt uses kube without using the pinned kube context that I didn't manage to trigger.
2. There's some case in which Tilt tries to use the pinned kube context but fails to do so correctly.
3. Something about your kube/tilt config differs from mine in a way that triggers this behavior.

FWICT, the only places in the code that touch kubectl are pretty straightforwardly using the pinned context, so I'm leaning against (1).

Could you try running Tilt with `--klog 7` and seeing what kubectl apply commands get logged?

**Comment by nicks** [comment] 2019-07-29 15:28
Also, could you double-check that you're running a recent version of Tilt? I think older versions of Tilt had this problem, but anything built in the last couple months should pin the context.

**Comment by majelbstoat** [comment] 2019-07-29 18:27
What I mean is the k8s objects were being applied to the production cluster.

I can be sure that I had the cluster pointed to dev when I started tilt, because I have a line at the top of the file that fails the Tiltfile if the cluster is not dev:

```
cluster = str(local('kubectl config current-context')).strip()
if (cluster != 'docker-desktop' and cluster != 'microk8s'):
    local("echo 'Not configured for local cluster' && exit 1")
```

I'll check out the version when i have access to the right machine tonight. but i believe it was v0.9.5, built 2019-07-25.

**Comment by tamer-hassan** [comment] 2019-07-30 08:23
happened to us earlier yesterday too in UAT when someone accidentally was in uat-cluster context instead of docker-desktop context when starting `tilt up`, and k8s_yaml in Tiltfile applied and therefore overwrite environment secrets and was really bad situation cuz everything was apparently down on the next deploy :(

**Comment by tamer-hassan** [comment] 2019-07-30 08:48
> I can be sure that I had the cluster pointed to dev when I started tilt, because I have a line at the top of the file that fails the Tiltfile if the cluster is not dev:
> 
> ```
> cluster = str(local('kubectl config current-context')).strip()
> if (cluster != 'docker-desktop' and cluster != 'microk8s'):
>     local("echo 'Not configured for local cluster' && exit 1")
> ```
> 
> I'll check out the version when i have access to the right machine tonight. but i believe it was v0.9.5, built 2019-07-25.

two slight notes to improve:
1. docker-for-desktop is the right context name (you missed "-for")
2. use native Tilt api call `k8s_context`
```
cluster = k8s_context()
if (cluster != 'docker-for-desktop' and cluster != 'microk8s'):
    local("echo 'Not configured for local cluster' && exit 1")
```
https://docs.tilt.dev/api.html#api.k8s_context

**Comment by maiamcc** [comment] 2019-07-30 16:12
> happened to us earlier yesterday too in UAT when someone accidentally was in uat-cluster context instead of docker-desktop context when starting `tilt up`, and `k8s_yaml` in Tiltfile applied and therefore overwrite environment secrets and was really bad situation cuz everything was apparently down on the next deploy :(

@tamer-hassan sorry, I'm confused: if you STARTED Tilt in the non-docker-desktop cluster, then this is all expected behavior and the thing you're looking for is some safeties around which cluster Tilt lets you mess around in, right? In which case your issue might be fixed by:
1. a line in your tiltfile like @majelbstoat's to bail if you're running in the wrong context
2. more visibility like #1900 
3. built-in safeties like #1096 

Or am I misunderstanding, and you had a problem with STARTING tilt in one kubecontext, externally switching contexts, and then tilt deploying to the NEW context (rather than pinning the old one)?

**Comment by maiamcc** [comment] 2019-07-30 16:13
> docker-for-desktop is the right context name (you missed "-for")
also, just to add, both `docker-for-desktop` and `docker-desktop` may be correct, depending on what version of docker you're running -- I'd assume @majelbstoat's works correctly for their setup :)

**Comment by majelbstoat** [comment] 2019-07-30 20:07
Yes, in the version of Docker I use, it is now 'docker-desktop'. (It was previously docker-for-desktop. I guess they changed it.) Thanks for the tip on k8s_context()!

And to confirm, this was with version `v0.9.5, built 2019-07-25`. I haven't yet tried to repro (because if I succeed, it trashes the production cluster which I then have to fix 😂).

**Comment by maiamcc** [comment] 2019-07-30 20:27
Oh ugh, cool, we'll look into it. Can you give us the output of `tilt doctor`, and tell us which contexts you switched between?

**Comment by majelbstoat** [comment] 2019-07-30 20:32
This is the output of tilt doctor, now. (Tilt is not currently running.)

```
Tilt: v0.9.5, built 2019-07-25
System: darwin-amd64
---
Docker
- Host: [default]
- Version: 1.40
- Builder: 2
---
Kubernetes
- Env: docker-for-desktop    // I am a bit confused by this, but did update docker recently, so 🤷🏼‍♂️.
- Context: docker-desktop
- Cluster Name: docker-desktop
- Namespace: default
- Container Runtime: docker
- Version: v1.14.3
```

I definitely started in cluster docker-desktop, or my guard would have failed. I must have switched context to `gke_pinian-app_us-central1-a_pinian-production` because that's the cluster I found the images in.

I don't recall whether I switched by using `kubectl config use-context` or from the Docker Kubernetes UI, but I don't *think* it matters. And sure, I can have a go at another cluster.

**Comment by majelbstoat** [comment] 2019-07-30 20:58
I've tried a few times and haven't been able to repro, even changing the context while it was starting up, or live updating something. If there's no other reports, you can probably put down to PEBKAC 🤷🏼‍♂️. I'll update if I see it happen again 🙂

**Comment by maiamcc** [comment] 2019-07-31 19:41
Well, glad to hear it's not giving you trouble anymore! 😅

@majelbstoat I'm closing this issue for now, but feel free to re-open if you manage to replicate.

@tamer-hassan I left some comments above -- my understanding is that the thing that you're having trouble with isn't quiiite what this issue is reporting, and a better fit for #1900 or #1096, but let me know if that's not right!

**Closed by maiamcc** 2019-07-31 19:41 UTC
Labels: bug

**Comment by tamer-hassan** [comment] 2019-08-01 10:05
> @tamer-hassan I left some comments above -- my understanding is that the thing that you're having trouble with isn't quiiite what this issue is reporting, and a better fit for #1900 or #1096, but let me know if that's not right!

Sorry for the late reply. You're absolutely right. The issue was only when another developer ran `tilt up` while not in the correct (local) context. So the issues you cited are in fact right on the mark.
